<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/adminMaster.Master" AutoEventWireup="true" CodeBehind="addproductvarient.aspx.cs" Inherits="aforalux.Admin.addproductvarient" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        #ContentPlaceHolder1_chkoffer{
            width:15%;
            height:20px;

        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="body_wrap">

      <!-- backtotop - start -->
      <div class="backtotop">
        <a href="#" class="scroll">
          <i class="far fa-arrow-up"></i>
        </a>
      </div>
      <!-- backtotop - end -->

      <!-- preloader - start -->
      <!-- <div id="preloader"></div> -->
      <!-- preloader - end -->

      <!-- header_section - start
      ================================================== -->
      
      <!-- header_section - end
      ================================================== -->

      <!-- main body - start
      ================================================== -->
      <main>

        <!-- breadcrumb_section - start
        ================================================== -->
        
        <!-- breadcrumb_section - end
        ================================================== -->

        <!-- register_section - start
        ================================================== -->
        <section class="register_section sec_space_small">
          <div class="container">
            <div class="register_form_wrap text-center dashboard_wrap">
              <h2>Add Product Varient</h2>
               
                <div class="mt-4">
                    <div class="row">
                        <div>Category: <asp:Label runat="server" ID="catname"></asp:Label></div>
                    </div>
                     <div class="row">
                        <div>Sub Category: <asp:Label runat="server" ID="subcatname"></asp:Label></div>
                    </div>
                     <div class="row">
                        <div>Product Name: <asp:Label runat="server" ID="productname"></asp:Label></div>
                    </div>
                </div>
                        <asp:Label CssClass="alert-success p-2 position-absolute labelclassSuccess" runat="server" ID="lbltext" Text="Sub category has been added" Visible="false"></asp:Label> 

            </div>

                <div class="mt-4">
                  <div class="row">
                      <div class="col-sm-2">
                          <asp:DropDownList runat="server" CssClass="form-control" ID="ddlsize"></asp:DropDownList>
                      </div>
                       <div class="col-sm-2">
                           <asp:TextBox runat="server" ID="txtcolor" CssClass="form-control" placeholder="Color"></asp:TextBox>
                      </div>
                      <div class="col-sm-2">
                           <asp:TextBox runat="server" ID="txtstock" CssClass="form-control" placeholder="Stock"></asp:TextBox>
                      </div>
                       <div class="col-sm-2">
                           <asp:TextBox runat="server" ID="txtprice" CssClass="form-control" placeholder="Price"></asp:TextBox>
                      </div>
                       <div class="col-sm-4">
                          <div class="d-flex justify-content-center align-items-center">
                              <asp:CheckBox runat="server" ID="chkoffer" Text="Offer Available" OnCheckedChanged="chkoffer_CheckedChanged"  AutoPostBack="true" />
                           <div runat="server" id="divoffer">
                               <asp:TextBox runat="server" ID="txtoffer" CssClass="form-control" placeholder="Enter Offer price"></asp:TextBox>
                           </div>
                          </div> 
                      </div>
                  </div>
                    <div class="row">
                        <div class="text-center">
                            <asp:Button runat="server" ID="preview" Text="preview" class="btn btn_primary btn_rounded" OnClick="preview_Click" />
                        </div>
                    </div>
              </div>
                <div class="text-center mt-4 mb-4">
                    <asp:GridView runat="server" AutoGenerateDeleteButton="true" OnRowDeleting="grdproductvarient_RowDeleting" ID="grdproductvarient" Width="100%" >

                    </asp:GridView>
                </div>
                <div class="text-center">
                      <asp:Button runat="server" ID="Save" Text="Save" class="btn btn_primary btn_rounded" OnClick="Save_Click" />
           
                </div>
          </div>
        </section>
        <!-- register_section - end
        ================================================== -->

      
      </main>
      <!-- main body - end
      ================================================== -->

      

    </div>
</asp:Content>
